version: 0.1

phases:
  pre_build:
    commands:
      - cd ./Server/src/
      - npm install
  build:
    commands:
      - npm build
      - npm test
reports:
  jest_reports:
    files:
      - testReport
    file-format: JUNITXML
    base-directory: ./Server/
